#!/bin/bash

displays=$(xrandr --listactivemonitors | awk '$4 != ""{print $4;}')

if [[ $1 && 0 -le $1 && $1 -le 100 ]]; then
    brightness=$(echo "scale=2; $1/100" | bc)
    for display in $displays; do
        xrandr --output $display --brightness $brightness
    done
fi
